source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'event-calendar', :require => 'event_calendar'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
# To use ActiveModel has_secure_password
gem 'bcrypt-ruby',:require => "bcrypt"

# Use unicorn as the web server
# gem 'unicorn'
gem 'rake'
# Deploy with Capistrano
# gem 'capistrano'
gem 'nifty-generators'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
gem "mocha", :group => :test
